### ISSUE TITLE
Maven Package Charts

### ISSUE THREAD

**Issue by rbbl-dev** [bytebeats/compose-charts#19]
Hello, is there a maven package for the charts?

**Comment by TalosDx** [comment]
If you need help write, I had some experience with maven central

**Comment by bytebeats** [comment]
@TalosDx Sorry, I'm just a little tired. I'll do this in this weekend.

**Comment by bytebeats** [comment]
@rbbl-dev @TalosDx I have published `compose-charts` to maven central.
Click [README](https://github.com/bytebeats/compose-charts/blob/master/README.md#L25) to know about how to use `compose-charts` dependency.
