### ISSUE TITLE
Suggesion: X value formatter

### ISSUE THREAD

**Issue by ArnyminerZ** [bytebeats/compose-charts#22]
First of all, congrats for the API, it's awesome and works like a glance.

But just like in the Y axis there's a value formatter to customize how it's displayed, it'd be really useful to have the same on the X axis.

Thanks in advance, keep working! This is awesome 🚀

**Comment by bytebeats** [comment]
@ArnyminerZ 0.1.1 is released. And X value formatter is supported.
