### ISSUE TITLE
Feature request: custom BarChart max value

### ISSUE THREAD

**Issue by crizzis** [bytebeats/compose-charts#25]
Right now, BarChart max y value is fixed on the highest data point. It would be nice to be able to set the top y value to some other value. I have some extra markers I need to put at certain Y values beyond the top bar and I'm struggling to make it render correctly.

**Comment by crizzis** [comment]
Relevant PR: https://github.com/bytebeats/compose-charts/pull/26

**Comment by crizzis** [comment]
@bytebeats Thanks a lot! Any chance to get this update published to Maven?

**Comment by bytebeats** [comment]
@crizzis I planned to release 0.1.2 in this weekends. If everything is OK, you'll be able to upgrade in the NEXT Monday.

**Comment by bytebeats** [comment]
Version 0.1.2 is released.
