### ISSUE TITLE
Expose LineChartData's properties to public

### ISSUE THREAD

**Issue by hoangnguyen92dn** [bytebeats/compose-charts#30]
Hi 👋 Firstly, I wanna say thank you for your helpful compose chart library. You saved me a lot of time to implement the LineChart on my current project.

I am using LineChart from your library however the design looks a bit different from yours, that's why I have do to some stuff to customize the chart. I need to determine the max and min values to draw the text label on top of the points. So I am asking for the solution that we could expose the properties to public rather than private/internal 😄 

https://github.com/bytebeats/compose-charts/blob/b853af66e8b4ca71e76c8d056b90f34af9211ac7/charts/src/main/java/me/bytebeats/views/charts/line/LineChartData.kt#L19-L32

**Comment by bytebeats** [comment]
Let me try to upgrade this project in this week. Glad the project helped you once.

**Comment by bytebeats** [comment]
some internal `val`s will be changed into `public` when new version is released.
